### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mpascariu** [timriffe/DDSQLtools#1]
Hi Tim,

I am trying to install the package from Github but something is not working. See below the error.

```
> library(devtools)
> install_github("timriffe/DDSQLtools")
Downloading GitHub repo timriffe/DDSQLtools@master
from URL https://api.github.com/repos/timriffe/DDSQLtools/zipball/master
Installing DDSQLtools
Installation failed: values must be type 'character',
 but FUN(X[[1]]) result is type 'logical'
```

**Comment by timriffe** [comment]
Hey MP thx. Will investigate and fix this tonight. Not really anything to install yet however. Fairly clean slate.

**Comment by timriffe** [comment]
Hi MP, I had the same issue but then updated devtools like this:
```
update.packages()
devtools::install_github("r-lib/devtools")
```
and then it works fine. The issue was with specifying a remote repo in the `DESCRIPTION` file (DemoTools gets installed from it's github repo automatically on a DDSQLtools install). Should be good if you update.

**Comment by mpascariu** [comment]
Got it. Thanks!
