### ISSUE TITLE
add `verbose` argument to toggle argument messaging

### ISSUE THREAD

**Issue by timriffe** [timriffe/DDSQLtools#4]
Console messages on other (optional) arguments and their default values are great, but perhaps toggle this behavior with:
`verbose = TRUE`
as a default argument. This could be added to any wrapper where pertinent.

**Comment by timriffe** [comment]
also note that the additional arguments are ` "optional"`

**Comment by mpascariu** [comment]
Fixed in the `mpascariu` branch. Coming soon to `master` too.
