### ISSUE TITLE
`doHeaping()` argument defaults

### ISSUE THREAD

**Issue by timriffe** [timriffe/DDSQLtools#5]
`doHeaping()` gives the following defaults:
```
ageMin = 10
ageMax = 90
```
which are intended to define an age range (inclusive at the top). However, the `"WI"` method takes an `Ages = c(95,100,105)` argument, with essentially the same purpose, but with a clearly different default range. I should probably change it on the `DemoTools` side to also rely on `ageMin` and `ageMax`, but this will introduce a conundrum here, since different available methods would have different appropriate defaults. Is the solution to remove `ageMin` and `ageMax` from the top level in `doHeaping()`?

The same phenomenon could arise elsewhere.

**Comment by mpascariu** [comment]
Not sure what the solution is but if I remove `ageMin` and `ageMax` the function will not be affected. I guess all the methods called in `doHeaping()` have default `ageMin` and `ageMax`.

The messages will pop-up informing the user about these arguments.

**Comment by mpascariu** [comment]
`ageMin` and `ageMax` removed from all `do` functions. The messages are working like a charm.
The changes are coming soon to `master` too.
