### ISSUE TITLE
`doSmoothing()`

### ISSUE THREAD

**Issue by timriffe** [timriffe/DDSQLtools#6]
`doSmoothing()` calls `agesmth()`, which I think is the best strategy, since `agesmth()` handles tails.
1) would be nice to have console message as with `doHeaping()` to indicate other arguments available and their defaults. 
2) `"agesmth"` is presently recorded in the `"DataProcessType"` column, but that doesn't inform about which method was used. Maybe e.g. `"agesmth-beers"`, a simple concatenation?

**Comment by mpascariu** [comment]
1. `doSmoothing()` calls only `agesmth()`. All the `agesmth()` arguments with their default values are visible in `doSmoothing()`; and the entire documentation is imported from `DemoTools`. I do not think the messages are needed here.

2. We can do as you suggest but the downside is that we will lose consistency. `"DataProcessType"` will no longer represent the function called from `DemoTools` like in the other `do` functions.

**Comment by mpascariu** [comment]
1. Do we agree on this?
2. DONE.

**Comment by timriffe** [comment]
(1) I'm not sure yet how to record it, we can get a quick answer from Patrick on this one.

**Comment by mpascariu** [comment]
This has been discussed with Patrick and fixed (#11) in version `0.01.010`.
